### ISSUE TITLE
Unable to import mindocr. No module named 'mindocr.data'

### ISSUE THREAD

**Issue by chernobaevigor** [mindspore-lab/mindocr#162]
MindOCR is not usable. 

The way I installed mindocr:
1. git clone https://github.com/mindspore-lab/mindocr.git
2. cd mindocr
3. pip install -r requirements.txt
4. python setup.py build
5. python setup.py install
6. Trying to run 'python -c "import mindocr"' anywhere outside mindocr gives the error:
```
ModuleNotFoundError: No module named 'mindocr.data'
```

The root cause seems to be in broken import statements at:
1. mindocr/utils/vizualize.py
2. mindocr/data/transforms/general_transforms.py

**Comment by HaoyangLee** [comment]
Fixed. PR #161 #159 #147

**Comment by chernobaevigor** [comment]
Still unable to import mindocr. Have checked with:

git+https://github.com/mindspore-lab/mindocr.git@0effe3b4d2b15c7f545309afa5a2ef4a09a6bf5f

git+https://github.com/mindspore-lab/mindocr.git@035e5c52433e25d8d6f72082b7c832409dc86f9f

Steps to reproduce:
pip install git+https://github.com/mindspore-lab/mindocr.git@v0.1.0
pip install git+https://github.com/mindspore-lab/mindocr.git@main

**Comment by chernobaevigor** [comment]
UPD. The issue has been resolved by creating empty conda environment and installing mindocr via requirements.txt

**Comment by SamitHuang** [comment]
> UPD. The issue has been resolved by creating empty conda environment and installing mindocr via requirements.txt

closed as resolved
